/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/homepage`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/layout`; params?: Router.UnknownInputParams; } | { pathname: `/not-found`; params?: Router.UnknownInputParams; } | { pathname: `/routes.d`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/app/layout`; params?: Router.UnknownInputParams; } | { pathname: `/components/Bio`; params?: Router.UnknownInputParams; } | { pathname: `/components/Contact`; params?: Router.UnknownInputParams; } | { pathname: `/components/Experience`; params?: Router.UnknownInputParams; } | { pathname: `/components/Header`; params?: Router.UnknownInputParams; } | { pathname: `/components/ProfileImage`; params?: Router.UnknownInputParams; } | { pathname: `/components/Projects`; params?: Router.UnknownInputParams; } | { pathname: `/components/Skills`; params?: Router.UnknownInputParams; } | { pathname: `/components/SocialLinks`; params?: Router.UnknownInputParams; } | { pathname: `/screens/MainScreen`; params?: Router.UnknownInputParams; } | { pathname: `/types/expo-router.d`; params?: Router.UnknownInputParams; } | { pathname: `/types/social`; params?: Router.UnknownInputParams; } | { pathname: `/utils/constants`; params?: Router.UnknownInputParams; } | { pathname: `/[...unmatched]`, params: Router.UnknownInputParams & { unmatched: (string | number)[]; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/homepage`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/layout`; params?: Router.UnknownOutputParams; } | { pathname: `/not-found`; params?: Router.UnknownOutputParams; } | { pathname: `/routes.d`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/app/layout`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Bio`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Contact`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Experience`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Header`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ProfileImage`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Projects`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Skills`; params?: Router.UnknownOutputParams; } | { pathname: `/components/SocialLinks`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/MainScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/types/expo-router.d`; params?: Router.UnknownOutputParams; } | { pathname: `/types/social`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/constants`; params?: Router.UnknownOutputParams; } | { pathname: `/[...unmatched]`, params: Router.UnknownOutputParams & { unmatched: string[]; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/homepage${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/layout${`?${string}` | `#${string}` | ''}` | `/not-found${`?${string}` | `#${string}` | ''}` | `/routes.d${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/app/layout${`?${string}` | `#${string}` | ''}` | `/components/Bio${`?${string}` | `#${string}` | ''}` | `/components/Contact${`?${string}` | `#${string}` | ''}` | `/components/Experience${`?${string}` | `#${string}` | ''}` | `/components/Header${`?${string}` | `#${string}` | ''}` | `/components/ProfileImage${`?${string}` | `#${string}` | ''}` | `/components/Projects${`?${string}` | `#${string}` | ''}` | `/components/Skills${`?${string}` | `#${string}` | ''}` | `/components/SocialLinks${`?${string}` | `#${string}` | ''}` | `/screens/MainScreen${`?${string}` | `#${string}` | ''}` | `/types/expo-router.d${`?${string}` | `#${string}` | ''}` | `/types/social${`?${string}` | `#${string}` | ''}` | `/utils/constants${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/homepage`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/layout`; params?: Router.UnknownInputParams; } | { pathname: `/not-found`; params?: Router.UnknownInputParams; } | { pathname: `/routes.d`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/app/layout`; params?: Router.UnknownInputParams; } | { pathname: `/components/Bio`; params?: Router.UnknownInputParams; } | { pathname: `/components/Contact`; params?: Router.UnknownInputParams; } | { pathname: `/components/Experience`; params?: Router.UnknownInputParams; } | { pathname: `/components/Header`; params?: Router.UnknownInputParams; } | { pathname: `/components/ProfileImage`; params?: Router.UnknownInputParams; } | { pathname: `/components/Projects`; params?: Router.UnknownInputParams; } | { pathname: `/components/Skills`; params?: Router.UnknownInputParams; } | { pathname: `/components/SocialLinks`; params?: Router.UnknownInputParams; } | { pathname: `/screens/MainScreen`; params?: Router.UnknownInputParams; } | { pathname: `/types/expo-router.d`; params?: Router.UnknownInputParams; } | { pathname: `/types/social`; params?: Router.UnknownInputParams; } | { pathname: `/utils/constants`; params?: Router.UnknownInputParams; } | `/${string}` | { pathname: `/[...unmatched]`, params: Router.UnknownInputParams & { unmatched: (string | number)[]; } };
    }
  }
}
